### ISSUE TITLE
FEAT: Add cypress screenshots in YAML file

### ISSUE THREAD

**Issue by Anissa3005** [ourjapanlife/findadoc-web#577]
# Problem
When tests fails on our CI, we can't view cypress. By adding screenshots to our cypress YAML file we can see what is happening when a test is failing.

# Success
Add screenshots to YAML file

### Requirements

- [ ] Add screenshots to the cypress yaml file

# Implementation notes
This is what you have to add in the cypress yaml file
```
            - name: Upload screenshots
              uses: actions/upload-artifact@v3
              if: failure()
              with:
                name: cypress-screenshots
                path: cypress/screenshots
```
